name: CI

on:
  push:
    branches: [master, stable, next]
  pull_request:
    branches: [master, stable, next]

  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update packages list
        run: sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install -y libtool autoconf automake unzip

      - name: Autogen
        run: ./autogen.sh -s

      - name: Install Android NDK
        run: |
          mkdir /tmp/android && cd /tmp/android
          curl -o ndk.zip -L https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip ndk.zip && rm -f *.zip && mv android-ndk* ndk

      - name: Android compilation
        run: |
          env ANDROID_NDK_HOME=/tmp/android/ndk ./dist-build/android-aar.sh

      - uses: actions/upload-artifact@v3
        with:
          name: aar
          path: ./libsodium-*.aar
          retention-days: 3
